# Generated by Django 5.1.6 on 2025-02-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ParkMenu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateTimeField()),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="nastani/"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="kategorija",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Комбинации/Combos", "Combo"),
                    ("Кафе/Coffee", "Kafe"),
                    ("Чај/Tea", "Caj"),
                    ("Вода/Water", "Water"),
                    ("Цедени Сокови/Fresh-Juices", "fres"),
                    ("Сокови/Juice", "sokovi"),
                    ("Топли Напитоци/Hot Drinks", "topli"),
                    ("Пиво/Beers", "Pivo"),
                    ("Алкохол/Alchohol Drinks", "alkohol"),
                    ("Енергетски/Energetic Drinks", "energetski"),
                    ("Коктели/Cocktails", "kokteli"),
                    ("Вино/Wine", "vino"),
                    ("Шампајн/Champagne", "sampajn"),
                    ("Безалкохолни коктели/Non-alcoholic Cocktails", "bezalkoholni"),
                    ("Наргиле/Shisha", "nargile"),
                    ("Сладолед/Ice-Cream", "sladoled"),
                    ("Апетисани/Appetizers", "Apetisani"),
                    ("Шотови/Shots", "shot"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="opis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
