# Generated by Django 5.1.6 on 2025-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ParkMenu", "0002_event_alter_product_kategorija_alter_product_opis"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="reservations_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
